# Generated by Django 4.1.2 on 2022-12-15 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appblog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='post',
            name='imagen',
        ),
    ]
