# Generated by Django 4.1.2 on 2022-12-15 20:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appblog', '0002_remove_post_fecha_remove_post_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
