# Generated by Django 4.1.2 on 2022-12-18 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appblog', '0008_alter_post_imagen_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
